### ISSUE TITLE
Enable navigation header

### ISSUE THREAD

**Issue by sanxy** [TheDorkKnightRises/Notes-App#1]
Your activity_main.xml is missing the navigation header. Here is the code to enable the header
`<android.support.design.widget.NavigationView
        android:id="@+id/nav_view"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:fitsSystemWindows="true"
        app:headerLayout="@layout/nav_header_main"
        app:menu="@menu/menu_drawer" />`

Adding  
`app:headerLayout="@layout/nav_header_main"`
 will enable the navigation header because the header is already present in the project file.

**Comment by TheDorkKnightRises** [comment]
This is a deliberate design decision to eliminate the nav header because it serves no functionality. If I decide to add some sort of accounts/profiles system to the app later, then it might come back, but for now, I think I'll keep it without a header.
