### ISSUE TITLE
Releases no longer available here?

### ISSUE THREAD

**Issue by IzzySoft** [TheDorkKnightRises/Notes-App#4]
According to Playstore, there's already a version 3.2.1 – but the latest tag here at Github is for v2.0. Are you no longer tagging releases? Are the APK files no longer available here? Please continue tagging your releases, and attaching the APK to the tag. Thanks!

**Comment by IzzySoft** [comment]
@TheDorkKnightRises Any ETA? 😃 And while on it: could you please clarify what license you use for this project?

**Comment by TheDorkKnightRises** [comment]
> @TheDorkKnightRises Any ETA? 😃 And while on it: could you please clarify what license you use for this project?

I have just created a new release on GitHub, check it out! However, I was making use of GitHub releases to distribute the app before it was on Play Store, and have since then switched to Play Store as the primary source, so I cannot guarantee that future releases will be tagged on GitHub!
As for license, this was one of my first projects (and also notes apps are a common idea) so I did not think anyone would be seriously interested in making use of this code. So on a whim I did not use any existing standard license but wrote my own terms, which are present in the README and in LICENSE file.

Note that this app has not received updates in a very long time, and will probably not receive them in the near future. Maybe once I am out of college (I am currently on my final semester) I will pick it up again and give it some much-needed updates! In the meantime, contributions are welcome!

**Comment by IzzySoft** [comment]
Thanks a lot! My updater just grabbed it, should show up [here](https://apt.izzysoft.de/fdroid/index/apk/thedorkknightrises.notes) in half an hour (that's the way I contribute, not being a dev). I hope you will still provide the APK here with future releases – for those outside of playstore, using free devices :smile: 

As for the license: I had hoped for a known name the F-Droid system understands… Well, then I can't point it out and folks have to live without that (or check here).

**Comment by TheDorkKnightRises** [comment]
Sure, I will try to provide releases here if I remember in 6 months' time! 😋 
And well, I don't know much about maintaining your own F-Droid repositories, but would it be possible for you to show license as "Custom" and make it a link to the LICENSE file here (or the README)?
Anyway, I will close this issue for now! Thanks for your contribution by making apps available to those who do not use Play Services!

**Comment by IzzySoft** [comment]
Ouch, now we got a problem: You added more Trackers and thus exceeded the limit of what's acceptable:

* Google Ads (Advertisement)
* Google AdMob (Advertisement)
* Doubleclick (Advertisement)
* Firebase Ads (Advertisement)
* Firebase Analytics (Mobile Analytics)

plus

* Google Mobile Services
* Firebase

That makes 7 proprietary items – which would be 7 too much for the official repo, and at least 3 too much for mine. Couldn't you at least remove some of the ad modules? Unfortunately, I for now must remove the update again due to that, and disable auto-updates. Please let me know when you have a version with less trackers.

For the license: No, that's just a plain text field for the license name, sorry.

**Comment by TheDorkKnightRises** [comment]
Actually yeah, Google Ads are currently broken anyway (there were some changes to the ads stuff that I haven't had time to update my app for, so ads don't show).
So I could remove them for now. I'll create a new issue for that and try to do it over the weekend.

**Comment by IzzySoft** [comment]
Wow :bowing_man: I thank you in the name of myself and all the other tin foil hats using my repo :+1: That's great news! I'll follow the other issue then to get a ping when the release is available, to I trigger the update on my end (and re-enable auto-updates).

**Comment by IzzySoft** [comment]
Unfortunately, the last APK has a problem:

```
ERROR: No signing certificates found in repo/thedorkknightrises.notes_3.3.apk
WARNING: Skipping 'thedorkknightrises.notes_3.3.apk' with invalid signature!
```

There seems to be a bug in Android Studio currently, as that happens to quite some apps these days…

**Comment by TheDorkKnightRises** [comment]
> Unfortunately, the last APK has a problem:
> 
> ```
> ERROR: No signing certificates found in repo/thedorkknightrises.notes_3.3.apk
> WARNING: Skipping 'thedorkknightrises.notes_3.3.apk' with invalid signature!
> ```
> There seems to be a bug in Android Studio currently, as that happens to quite some apps these days…

I guess there's not much I can do but wait for Android Studio to fix it right?
I did just push an updated release, you can give it a shot (it should probably throw the same error cuz I didn't do anything different, but worth a shot?)

**Comment by IzzySoft** [comment]
The other devs somehow got it fixed with another build (and no, the currently attached APK didn't solve it, I just tried). No idea how (maybe they signed it manually using `apksigner sign`). And that it might be a bug in Android Studio is just a guess of mine, as it happened so often recently (but not for all apps).

Would the app not have GMS remaining, I had suggested asking F-Droid to include it…

Well, I've set it to manual mode now, hoping it will be solved with the next version then… Thanks a lot for your help and patience!

**Comment by IzzySoft** [comment]
Okay, just got told by another dev what should do the trick: Please tick the v1 signature as well when signing, see [here](https://github.com/passwordmaker/android-passwordmaker/issues/46#issuecomment-467720811). Could you give that a try?

**Comment by TheDorkKnightRises** [comment]
Yeah I always check both boxes for V1 and V2 signatures. I guess that's not it in this case.

**Comment by IzzySoft** [comment]
OK, thanks. In the linked case, v1 was not checked originally – and when checked, it worked. So it seems different causes lead to a similar looking issue. Makes it harder to solve…

**Comment by IzzySoft** [comment]
Just wondering, @TheDorkKnightRises – are you still maintaining the app? Looks dormant since our last contact, for about 3 years now.

**Comment by TheDorkKnightRises** [comment]
> Just wondering, @TheDorkKnightRises – are you still maintaining the app? Looks dormant since our last contact, for about 3 years now.

@IzzySoft Nope, unfortunately this project is not being maintained for a couple of years now. In fact, I have not worked on any Android dev projects in that time, due to other responsibilities.

**Comment by IzzySoft** [comment]
Thanks for the fast reply! Then I'll mark it such in my repo now and exclude it from the apps I have to check manually for updates. Maybe you want to archive the repository then to make it clear, and/or place a corresponding note in the Readme?
