### ISSUE TITLE
Google Ads broken due to native express ads being unsupported

### ISSUE THREAD

**Issue by TheDorkKnightRises** [TheDorkKnightRises/Notes-App#5]
AdMob removed support for native express ads, so currently ads do not show.
It is suggested to switch to conventional banner ads.

**Comment by TheDorkKnightRises** [comment]
@IzzySoft You may want to follow this issue 😄

**Comment by IzzySoft** [comment]
I'm following. It's suggested to remove Google (or failing to do so, at least their ad and tracker modules 🤣)

Thanks for accepting the challenge!

**Comment by TheDorkKnightRises** [comment]
Removed ads in latest release (version 3.3)

**Comment by IzzySoft** [comment]
Thanks! Can you now also add the certificates?

```
ERROR: No signing certificates found in repo/thedorkknightrises.notes_3.3.apk
WARNING: Skipping 'thedorkknightrises.notes_3.3.apk' with invalid signature!
```
